$('#slide_destination').owlCarousel({
    items:2,
    loop:true,
    margin:30,
    responsive:{
        0:{
            items:1
        },
        768:{
            items:2
        },
        992:{
            items:3
        }
    }
});
